# Exercise 1: NumPy: Create an array with values ranging from 50 to 100

In [18]:
import numpy as np
import sys

#create Numpy array using arange from 50 to 100
NumP = np.arange(50,101)
print(NumP)


[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


# Exercise 2: Add a border around an existing array
Hint: np.pad()

In [62]:
## Use Padding around the existing array NumP
#Signature: np.ones(shape, dtype=None, order='C')
#Signature: np.pad(array, pad_width, mode='constant', **kwargs)

#Create 3*3 ones NumPy Array
Org_nparray = np.ones(shape=(3,3), dtype=None,order='F')

#print
print("Original array: ")
print(Org_nparray)

#Padding around the Array
np_pad = np.pad(Org_nparray, pad_width=1)

#print
print("0 on the border and 1 inside in the array : ")
print(np_pad)

Original array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array : 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# Exercise 3: Convert a list and tuple into arrays

In [97]:
#original List/ Tuple
orig_list = [1,2,3,4,5,6,7,8]
orig_tuple = ((1,2,3,4),(5,6,7,8))

#Convert list to array
print("List to Array:\n",np.array(orig_list))

#Convert tuple to array
print("\nTuple to Array: \n",np.array(orig_tuple))

#Use np.asarray to convert to numpy ndarray
#Signature: np.asarray(a, dtype=None, order=None)
print("\nList to Array:", "\n",np.asarray(orig_list))
print("\nTuple to Array:", "\n",np.asarray(orig_tuple))

List to Array:
 [1 2 3 4 5 6 7 8]

Tuple to Array: 
 [[1 2 3 4]
 [5 6 7 8]]

List to Array: 
 [1 2 3 4 5 6 7 8]

Tuple to Array: 
 [[1 2 3 4]
 [5 6 7 8]]


# Exercise 4: Convert the values of Centigrade degrees into Fahrenheit degrees
Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]

In [105]:
Fahrenheit_Array = np.array([0., 12., 45.21, 34., 99.91])

#°C = (°F - 32)/1.8
Centigrade_Array = (Fahrenheit_Array - 32)/ 1.8
print("Values in Fahrenheit degrees: \n", Fahrenheit_Array)
print("\nValues in  Centigrade degrees: \n", Centigrade_Array)

Values in Fahrenheit degrees: 
 [ 0.   12.   45.21 34.   99.91]

Values in  Centigrade degrees: 
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [61]:
Nmpy_array = np.array([[1,1],[2,2],[3,3]])
Nmpy_size = np.size(Nmpy_array)
print("Size: ", Nmpy_size)
print("length: ", len(Nmpy_array))
print("memory size of  1st array: ",Nmpy_array[0].size*Nmpy_array[0].itemsize)
print(np.byte(Nmpy_array[0].itemsize))
print(Nmpy_array[0].size)

Size:  6
length:  3
memory size of  1st array:  8
4
2


# Exercise 6: Get the unique elements of an array

In [78]:
#Original array:
Orig_array_1 = [10, 10, 20, 20, 30, 30]
Orig_array_2 = [[1, 1],[2, 3]]

#Typecast to Numpy array
uni_array_1 = np.array(Orig_array_1)
uni_array_2 = np.array(Orig_array_2)

print("Original array: ", Orig_array_1)

#Get Unique elements in the array
print("Unique elements of the above array: ","\n",np.unique(uni_array_1))

print("\nOriginal array: ", Orig_array_2)

#Get Unique elements in the array
print("Unique elements of the above array: ","\n",np.unique(uni_array_2))

Original array:  [10, 10, 20, 20, 30, 30]
Unique elements of the above array:  
 [10 20 30]

Original array:  [[1, 1], [2, 3]]
Unique elements of the above array:  
 [1 2 3]


# Exercise 7: Change the dimension of an array
Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns

In [87]:
#Original Array
Orig_array_dim = [1,2,3,4,5,6,7,8,9]
#to Numpy array
Nmpy_array_dim = np.array(Orig_array_dim)
print("Original array: \n",Nmpy_array_dim)

print("Change array shape to (3, 3) -> 3 rows and 3 columns \n",Nmpy_array_dim.reshape(3,3))



Original array: 
 [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [106]:
"""
Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.
"""

#Linspace used to create array
oneDarray = np.linspace(2.5,6.5,num=30)
print("1-D array of 30 evenly spaced elements between 2.5. and 6.5: \n\n", oneDarray)

1-D array of 30 evenly spaced elements between 2.5. and 6.5: 

 [2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


# Exercise 9: Convert 1-D arrays as columns into a 2-D array
Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]

In [136]:
array_1 = [10,20,30]
array_2 = [40,50,60]
npy_array_1 = np.array(array_1)
print("Array1: \n", npy_array_1)
npy_array_2 = np.array(array_2)
print("Array2: \n", npy_array_2)
print("\nConverted array \n",np.stack((npy_array_1,npy_array_2), axis=1))

Array1: 
 [10 20 30]
Array2: 
 [40 50 60]

Converted array 
 [[10 40]
 [20 50]
 [30 60]]


# Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [157]:
"""Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
"""

Orig_Zeroes_Array = np.zeros((5,5))

print("Original array:\n", Orig_Zeroes_Array)

Orig_Zeroes_Array = Orig_Zeroes_Array + np.arange(5)
print("\nRow values ranging from 0 to 4.\n",Orig_Zeroes_Array)

Original array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Row values ranging from 0 to 4.
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [173]:
#Create array in range 1 to 100
nmpy_rnge_array = np.arange(1,100)
#print rage array
print("Numpy array in range 1 to 100: \n",nmpy_rnge_array)

#Have only Mulitples of 3 or 5 in the created array
mult_3_5_array = nmpy_rnge_array[(nmpy_rnge_array%3 ==0)|(nmpy_rnge_array%5==0)]
print("\nArray with multiples of 3 or 5 below 100: \n",mult_3_5_array)

print("\nSum of all the multiples of 3 or 5 below 100: ",sum(mult_3_5_array))

Numpy array in range 1 to 100: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]

Array with multiples of 3 or 5 below 100: 
 [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]

Sum of all the multiples of 3 or 5 below 100:  2318


# Exercise 12: Combine a one and a two dimensional array together and display their elements

In [210]:
#create One Dimensiona Array
oneDArray = np.arange(0,4)

#create Two Dimensional Array
twoDArray = np.arange(0,8).reshape(2,4)

print("One dimensional array:\n{}".format(oneDArray),"\n")
print("Two dimensional array:\n{}".format(twoDArray),"\n")

#Combine one and a two dimensional array already created
print("Combined one and two dimensional array:")
for x, y in np.nditer([oneDArray,twoDArray]):
    print("{}:{}".format(x,y))   
    #print("%d:%d" % (x,y))

One dimensional array:
[0 1 2 3] 

Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]] 

Combined one and two dimensional array:
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


# Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array

In [221]:
#Create an Numpy array
orig_nmpy_array = np.array([[0.42436315, 0.48558583, 0.32924763],
 [0.7439979,  0.58220701, 0.38213418],
 [0.5097581,  0.34528799, 0.1563123 ]])

print("Original array:\n{}".format(orig_nmpy_array))

#Replace all elements of the said array with .5 which are greater than .5
orig_nmpy_array[orig_nmpy_array >.5]=0.5
print("\nReplace all elements of the said array with .5 which are greater than .5:\n{}".format(orig_nmpy_array))



Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]

Replace all elements of the said array with .5 which are greater than .5:
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


# Exercise 14: Add a new row to an empty numpy array

In [264]:
#Create an empty array
#Docstring: empty(shape, dtype=float, order='C')
empty_numpy_array = np.empty((0,3),int)

print("Empty Array:\n{}".format(empty_numpy_array))

#Create new 2 dimension arrays to be added
arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6]])

#Signature: np.append(arr, values, axis=None)
empty_numpy_array = np.append(empty_numpy_array, arr1, axis=0)
empty_numpy_array = np.append(empty_numpy_array, arr2, axis=0)

print("\nAdding new rows to empty numpy array:\n{}".format(empty_numpy_array))

Empty Array:
[]

Adding new rows to empty numpy array:
[[1 2 3]
 [4 5 6]]


# Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis

In [289]:
arry_1 = np.arange(1,4)
arry_2 = np.arange(4,7)
print("Original Arrays: ")
print(arry_1)
print(arry_2)

# join both the arrays in axis=0 (Horizontal)
print("Sequence of arrays along a new axis = 0: \n{}".format(np.stack((arry_1, arry_2), axis=0)))
# join both the arrays in axis=1(Vertical)
print("Sequence of arrays along a new axis = 1: \n{}".format(np.stack((arry_1, arry_2),axis=1)))

Original Arrays: 
[1 2 3]
[4 5 6]
Sequence of arrays along a new axis = 0: 
[[1 2 3]
 [4 5 6]]
Sequence of arrays along a new axis = 1: 
[[1 4]
 [2 5]
 [3 6]]
